name: release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: 'windows-latest'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - run: dotnet publish --self-contained true --configuration Release --runtime win-x64 -p:PublishSingleFile=true --output .\pub

      - uses: actions/upload-artifact@v2
        with:
          name: FhirLoader.exe
          path: pub/FhirLoader.exe
